### ISSUE TITLE
请问为什么要遍历map获取值，不可以直接【tk.Claims.(jwt.MapClaims)["exp"]】吗？而且遍历到了也没有退出

### ISSUE THREAD

**Issue by fengyuan-liang** [sevtin/lark#2]
https://github.com/sevtin/lark/blob/d2421e2bfc6805b9238c5ee4635359881388f0ec/pkg/common/xgin/gin_token.go#L26-L29

**Comment by saeipi** [comment]
> ，value = range tk。声明.(jwt.MapClaims ) {

该方法已弃用
